name: Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup npm package
       run: npm init -y && npm install
     - name: Cypress run
       uses: cypress-io/github-action@v4.2.0
       with:
        start: npm start
     - name: Jest run
       run: npm test
     
